$$
\def\I{{\rm i}}
\def\qqqquad{\qquad\qquad}
\def\qfor{\qquad\hbox{for}\qquad}
\def\qwhere{\qquad\hbox{where}\qquad}
\def\ale#1{\begin{align}#1\end{align}}
\def\em{\epsilon_m}
\def\unit#1{{\rm #1}}
\def\com#1{\color{blue}{\textrm{#1}}} 
$$

# Lab1: Intro to Julia

In this lab you will gain familiarity with using Julia and the Jupyter notebook environment. 

This laboratory assignment is divided into two parts. 

**Time management is important in 365 labs. 
Have a solid attempt yourself. If you get stuck, be bold about requesting help. You should aim to move on to part 2 by ~ 2.30pm**.

## Instructions for submitting lab assignments
- Submit your lab by ___copying___ this notebook with your answers into `dropbox` on `pleiades` (phsi365 Desktop link > dropbox ). 

- __Rename your notebook to__ `Lab1_userID.ipynb` before submitting it by dragging it onto the dropbox folder. For example, if your login name is `365joe`, make the notebook called `Lab1_joe.ipynb`. 
- You can confirm submission (and resubmit up to the deadline), by repeating the process. If you are asked whether to replace the file, this confirms it has been successfully submitted to the dropbox. __Please confirm your submission__.

- __Due:__ 1pm Wednesday 4th March.

$\com{Grading comments will appear like this}$

---

# Part 1: Julia and Jupyter notebooks

In part 1 we want you to get a feel for how do do some basic calculations in julia. 

## Jupyter

- Follow the steps in the notebook and answer the questions by adding new cells below. A simple way to label them is to put a comment in the cell, e.g. # a) . 
    - To execute the code in the current cell, hit two keys together: `shift+enter`. 
    - You can write comments (including latex) in markdown by first creating a cell, then typing the sequence `esc-m` to switch to "markdown mode" (or use the toolbar). 
    - To switch the cell back to code mode, type `esc-y`. 
    - Other useful commands are `esc-a` (make cell above), `esc-b` (below), and `esc-dd` (delete current cell).

- To see all keyboard shortcuts, click on the palette button on the left border of the browser window (above the spanner). 

- Make sure you understand why `Julia` does what it does. 

Type the following commands (I will neglect the cell numbers) one-by-one into separate cells, and hit `shift+enter` to evaluate each cell. Check that you receive the same result:
```julia
In : 1
Out: 1
```
```julia
In : 1+1
Out: 2
```
```julia
In : 1+
Out: syntax: incomplete: premature end of input
```
```julia
In : ans
Out: 2
```
```julia 
In : x=3
Out: 3
```
Based on the first two inputs we may conclude that `Julia` can be used like any calculator. The second to last input shows that if no variable is assigned, it assigns the value of the calculation to `ans`. However, the third input produces an error message, telling us that our command was not a valid input that `Julia` could interpret. `Julia` tells us that the command ended prematurely, which is not suprising since addition is a binary operator and requires two arguments that are added together. 

As a matter of convenience, we can also see a summary of all defined variables, functions, and modules in the current julia session using the command `varinfo()`
    
Similarly to what we have just done above, type each command in a separate cell below. 

In [ ]:
1

In [ ]:
1+1

In [ ]:
1+

In [ ]:
ans

In [ ]:
x=3

In [ ]:
varinfo()

## Julia

1) Give a short answer to each question by adding new cells below.

```julia
a) cos(1) # does Julia use radians or degrees for trig functions?
b) ?cos # how many related functions does Julia suggest?
c) [1 2 3 4] # is there any difference between [1 2 3 4] and [1,2,3,4]?
d) a = 1 # Julia confirms this command by returning the result. How do you suppress the output? (only needed for the last command in a sequence).
e) b = [10 11 23 44]; b[3] # how do you pull out the last element of a vector?
f) 5:9 # what does the : (colon) operator do?
g) M = randn(4,3) # how can you create a random matrix of size 6980x314?
h) x=3; # can you write more than one command in a single line? If "yes", how?
```

In [ ]:
cos(1) #a) radians


In [ ]:
?cos #b) 12 related funtions

In [ ]:
[1 2 3 4] #c) this gives a row vector

In [ ]:
[1,2,3,4] #adding ',' gives a column vector

In [ ]:
a=1

In [ ]:
a=1; #d) adding semi colon after line suppresses the output 

In [ ]:
b = [10 11 23 44]; b[3]

In [ ]:
b = [10 11 23 44]; b[end] #e) using 'end' as the index we are able to pick out last element of the vector

In [ ]:
u = collect(5:9) #f) the colon essentially creats a range of integers between the two given numbers
                # we can form this range of number into a vector using the'collect command

In [ ]:
M = rand(6980,314) #g) creates random matrix of desired size

In [ ]:
x=3; y=4; z=5; #h) we can put multiple commands on one line by separating with semicolons

2) Answer each question using text in a separate cell below each command.

```julia
a) v=1:4; u = collect(v) # how can we make a column vector [1 2 ... 1000000]^T ?
b) w = transpose(v); w = v' # how can we transpose a matrix?
c) x = rand(3,3)+im*rand(3,3); transpose(x); x' # what is the difference between transpose and '?
d) M = rand(5,5); A=M[2:4,1:3] # what does this command do? 
e) b = collect(1:12); B=reshape(b,3,4) # what does the second argument of reshape stand for? If you are unsure, use ?
```

In [ ]:
v = 1:1000000; u = collect(v) #a) first creating range of numbers from 1 to 100000 then collecting 
                                #into column vector

In [ ]:
M = [1 2 ; 3 4]; #b) this gives us a 2x2 matrix
W = transpose(M); #we can transpose a matrix in the same way as we transpose a vector
[M W]             #shows M and W side by side, we can see W is the transpose of M

In [ ]:
x = rand(3,3)+im*rand(3,3); 
transpose(x) #c) this simply produces a transposed matrix

In [ ]:
x' #c) this transposes the matrix as well as taking the complext conjugate of the entries i.e. the adjoint

In [ ]:
M = rand(5,5); A=M[2:4,1:3] #d) this takes rows 2:4 and columns 1:3 of the matrix M and creates a new 
                            #matrix A from these entries of M

In [ ]:
b = collect(1:12); B=reshape(b,3,4) #e) takes the vector b and uses its entries to fill a 3x4 matrix
                                    #the second arguement '3' specifies the number of rows of the matrix

3) Choose "Kernel"; "Restart Kernel and Clear All Outputs" from the menu above. Enter each command below in a separate cell, evaluate it, and then answer the questions below
```julia
A = [1 1; -2 6]
B = [3 -5;7 2]
C = [1 2 3; 2 4 6; 10 11 12]
1+A; 1.+A; 1 .+A
one(A)+A
A+B
A-B
A*B
A.*B
@. A*B
A/B
A./B
A^2
A.^2
A.^B
3 .^A; 3.0 .^A
A+C
```

In [1]:
A = [1 1; -2 6]

2×2 Array{Int64,2}:
  1  1
 -2  6

In [2]:
B = [3 -5;7 2]

2×2 Array{Int64,2}:
 3  -5
 7   2

In [3]:
C = [1 2 3; 2 4 6; 10 11 12]

3×3 Array{Int64,2}:
  1   2   3
  2   4   6
 10  11  12

In [5]:
1+A; 1.+A; 1 .+A

LoadError: syntax: invalid syntax "1.+"; add space(s) to clarify

In [6]:
one(A)+A

2×2 Array{Int64,2}:
  2  1
 -2  7

In [7]:
A+B

2×2 Array{Int64,2}:
 4  -4
 5   8

In [8]:
A-B

2×2 Array{Int64,2}:
 -2  6
 -9  4

In [9]:
A*B

2×2 Array{Int64,2}:
 10  -3
 36  22

In [10]:
A.*B

2×2 Array{Int64,2}:
   3  -5
 -14  12

In [11]:
@. A*B

2×2 Array{Int64,2}:
   3  -5
 -14  12

In [12]:
A/B

2×2 Array{Float64,2}:
 -0.121951  0.195122
 -1.12195   0.195122

In [13]:
A./B

2×2 Array{Float64,2}:
  0.333333  -0.2
 -0.285714   3.0

In [14]:
A^2

2×2 Array{Int64,2}:
  -1   7
 -14  34

In [15]:
A.^2

2×2 Array{Int64,2}:
 1   1
 4  36

In [16]:
A.^B

2×2 Array{Int64,2}:
    1   1
 -128  36

In [17]:
3 .^A; 3.0 .^A

DomainError: DomainError with -2:
Cannot raise an integer x to a negative power -2.
Make x or -2 a float by adding a zero decimal (e.g., 2.0^-2 or 2^-2.0 instead of 2^-2), or write 1/x^2, float(x)^-2, x^float(-2) or (x//1)^-2

In [18]:
A+C

DimensionMismatch: DimensionMismatch("dimensions must match")

a) What does the second `2` in `2:2:6` mean?

b) What is the difference between `*` and `.*`? How about `^` and `.^`?

c) What does each element of `A.^B` give in `julia`?

d) What is the result of `A+C`? Why?

e) Find in the help system what the operator `/` does; give a short explanation.

f) Could you exponentiate `A` to `B`, i.e. `A^B`, or just element-wise? If "no", then what if the error message? If "yes", what is the result?

In [22]:
a = collect(2:2:6) #a) the second 2 specifies the step size between elements in the range specified

3-element Array{Int64,1}:
 2
 4
 6

b)using '*' performs normal matrix multiplication whereas '.*' multiplies together corresponding elements of the two matricies
'^' raises a matrix to a power in the standard way i.e. A^2 = A * A as defined by matrix multiplication
'.^' raises each entry in the matrix to a specified power

c) This raises each element in A to the power of the corresponding element in B

d) This produces an error "dimensions must match" because the dimensions of A and C differ and matrix addition is only defined for matrices of the same size

In [24]:
?/

search: / //



```
/(x, y)
```

Right division operator: multiplication of `x` by the inverse of `y` on the right. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 1/2
0.5

julia> 4/2
2.0

julia> 4.5/2
2.25
```


e) The / operator takes two arguements and essentially divides the first arguement by the second returning a float

In [27]:
A^B

MethodError: MethodError: no method matching ^(::Array{Int64,2}, ::Array{Int64,2})
Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::AbstractArray{T,2} where T) at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/dense.jl:546
  ^(::AbstractArray{T,2}, !Matched::Integer) where T<:Integer at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/dense.jl:408
  ^(::AbstractArray{T,2} where T, !Matched::Integer) at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/dense.jl:404
  ...

f) we cannot exponentiate A^B in julia as there is no matching method which takes a matrix and exponentiates it to another matrix in the way that we are trying to do.

# Part 2: Functions and vectorizing
This second part of the lab contains 2 problems which you should solve and discuss in this `Jupyter` notebook. The aim of this part of the lab is understand the value of putting hard-working code inside functions and calling the function. You will also learn about broadcasting, and timing code.

We have seen in lectures that a function can be defined as simply as `f(x)=x^2`. For more complicated functions, the general way to define a function in `julia` is, e.g:

```julia 
function f(x)
    a = cos(x)
    b = 3
    return a,b
end
```
and in this case, would be called for `x=3` with the command `a,b=f(3)`, assigning two numbers to variables `a`, `b` _outside the function_. Let's start working with julia functions.

## To vectorize or not to vectorize?

A common strategy in technical computing is to ___vectorize___ your code. This refers to the process of expressing your problem in terms of vectors or matrices and (hopefully) sparse matrices acting on them. This allows high level languages like Matlab to call efficient compiled C-libraries for linear algebra. In many languages (Matlab for example) vectorizing is essential because `for` loops are slow. 

Let's find out how what julia has to say about this by investigating a simple example in detail. 

We will need to know how to time code in julia. You can use the macro `@time` to time any expression, e.g.

```julia
@time f(x)
```

will give the evaluation time for `f(x)` with that value of `x`. 

A longer expression can be timed by using a `begin-end` block:

```julia
@time begin
...
end
```

Let's say we want to calculate the sum of the reciprocals of the first ten thousand cubes, i.e. 

$$s = 1^{-3}+2^{-3}+3^{-3}+\dots +10000^{-3},$$

an approximation to $\zeta(3)$, where the [Riemann-zeta function](https://en.wikipedia.org/wiki/Riemann_zeta_function)

$$\boxed{\quad\zeta(z)=\sum_{k=1}^\infty\frac{1}{k^z}\quad}$$

is an important function in several branches of Physics. 

Determine $s$ using `julia` in three different ways.

(a) Use a [for loop](https://docs.julialang.org/en/v1/manual/control-flow/#man-loops-1). You will need to initialize the sum outside the loop (`s=0.0`), and then to modify `s` inside the loop, use  `global s = ...`. This is a slight peculiarity of julia loops that it is good to be aware of. Notice also that the statement 
```julia
s=0.0
```
given directly to julia defines a global variable: ___all variables outside function definitions are global___. This also means they can often lead to slower code (harder for the compiler to reason about). Hence an important lesson in julia is: if speed matters to you always use functions. This is also good practice because ___it makes your code more reusable.___

Time this code. 

(b) Put your for loop inside a [function](https://docs.julialang.org/en/v1/manual/functions/#) `mysum1()`. Time this. __Note:__ the first time you call a function, the compiler does some extra work. So the true timing we are interested in is for any call _after_ the first one where it is defined (redefinitions count as definitions too!).

(c) Use only a single-line __vectorised__ `julia` expression to calculate $s$ (no function wrapper). If you haven't done this before, the strategy is to define a vector `n=[1 2 3 ... 10000]` (you can do this with a range object `1:10000`, even though it looks a bit different to a vector, it still behaves like one in most circumstances). Then perform local (dot) operations to achieve the result. You should be able to get this down to one very short expression that easily fits on one line. Time it.

(d) Wrap your single-line expression in a function `mysum2()` and time this. 

(e) Use the package [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl), and the macro `@btime` to compare more accurate timings for (b),(c),(d) (`@btime` averages over multiple calls, so the garbage collection is triggered. This is a more honest realistic time). What can you conclude about the speed of vectorizing (writing in terms of array operations), as compared with writing a `for` loop? Would you recommend vectorizing code in julia? Why? 

In [46]:
#a)
@time begin 
    s = 0.0   #initialises the sum

    for i = 1:10000 #dummy variable runs from 1 to 100000 to produce sequence
        global s = s + i^(-3) #each term in the sequence is added to the global variable 's' to keep track of the sum
    end
    print(s) #the total sum is presented after for loop has run
end

1.202056898160098  0.000523 seconds (20.03 k allocations: 313.484 KiB)


In [73]:
#b)
function mysum1() #same as a) but wrapped in a function
        s = 0.0   
        for i = 1:10000
            s = s + i^(-3)
        end
    return(s)
end

mysum1 (generic function with 1 method)

In [76]:
#b)
@time mysum1()

  0.000013 seconds (5 allocations: 176 bytes)


1.202056898160098

In [80]:
#c)
@time begin
    s = sum((1:10000).^(-3)) #first we create a range of numbers from 1 to 10000 then sum the reciprical of the cube of each
end

  0.000053 seconds (13 allocations: 78.516 KiB)


1.2020568981600943

In [82]:
#e)
function mysum2()
    s = sum((1:10000).^(-3));
    return(s)
end

mysum2 (generic function with 1 method)

In [83]:
@time mysum2()

  0.034176 seconds (213.91 k allocations: 11.522 MiB)


1.2020568981600943

In [86]:
#e)
using BenchmarkTools

@btime mysum1() #measuring time when using a for loop in a function

  10.379 μs (0 allocations: 0 bytes)


1.202056898160098

In [89]:
#e)
using BenchmarkTools

@btime s = sum((1:10000).^(-3)) #measuring time when using vectorizing

  7.332 μs (2 allocations: 78.20 KiB)


1.2020568981600943

In [90]:
#e)
using BenchmarkTools

@btime mysum2()  #measuring time when using vectorizing and wrapping in a function

  7.351 μs (2 allocations: 78.20 KiB)


1.2020568981600943

e) We can see from the examples above using @btime that for this processing vectorizing is very slightly faster. I woulod recommend vectorizing when larger scale projects are undertaken as these time differences may become more significant. We can also see that we can achieve the same result with vectorising in less code when compared to for loops so this could save time and improve efficiency when writing code.
